version: "3.9"

services:
  scraper-service:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - RABBIT_MQ_SERVER_URL=${RABBIT_MQ_SERVER_URL}
        - RABBIT_MQ_CHANNEL_NAME=${RABBIT_MQ_CHANNEL_NAME}
        - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
        - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    container_name: goscraper-service
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - aslipaydekho-network

  message-broker:
    image: rabbitmq:3.8.25-management-alpine
    container_name: scraper-message-broker
    hostname: scraper-rabbit
    ports:
      - 5672:5672   # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI
    volumes:
      - ${HOME}/dev-rabbitmq/data/:/var/lib/rabbitmq
      - ${HOME}/dev-rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
    networks:
      - aslipaydekho-network
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    env_file:
      - .env

networks:
  aslipaydekho-network:
    driver: bridge